template-file-path: ./Infra_cfn.yaml
parameters:
  BedrockModelId: amazon.nova-lite-v1:0
  EnvironmentName: test1
  MultiAgentDevMode: 'True'

tags:
  Name: 'genovia-notebook-gitsync'
  Project: 'Demo'